### ISSUE TITLE
引入样式报错 

### ISSUE THREAD

**Issue by zhucheng1991** [xinhaoxx/form-taro3-react#1]
@import '~form-taro3-react/dist/styles/index';    

引入样式就会报错   麻烦帮忙看下 就算我手动引入还是会报错
![1630577484081.jpg](https://i.loli.net/2021/09/02/c5hY9WnlJBtdbx8.jpg)
![1630563929282.jpg](https://i.loli.net/2021/09/02/MpsENgCzSZ7b9w5.jpg)

**Comment by xinhaoxx** [comment]
这个项目的样式使用的是 SCSS，你可以在 jsx 文件 import，而不是在 LESS 文件内 @import
